### ISSUE TITLE
Throw Uncaught TypeError when edit a ".phtml" file

### ISSUE THREAD

**Issue by snowtigersoft** [wakatime/atom-wakatime#2]
When edit a ".phtml" file, it throw an Uncaught TypeError exception.
Detail:
Uncaught TypeError: Cannot read property 'className' of undefined on line 401 at "node_modules/highlight.js/lib/highlight.js" file

**Comment by Cybnext** [comment]
This case may be fixed, but the underlying issue is still there.  I'm not really familiar with coffeescript so I've been trying my best to figure out a fix.  Either way the problem lies with the highlight.highlightAuto method. It appears to just lock up the thread when it's given source that it can't determine what language it is.

I have a .info file that completely locks up Atom. However, after commenting out the highlightAuto() call, nothing locks up.
