### ISSUE TITLE
Delay after saving

### ISSUE THREAD

**Issue by daveyjones** [wakatime/atom-wakatime#43]
The wakatime plugin is causing large delays after saving. This causes issues with my LESS compiler, which is suppose to run after saving but takes 10-20 seconds to run when wakatime is enabled.

**Comment by alanhamlett** [comment]
This is on Windows, Mac, or Linux?

The two places which could cause slowness are:

1. [finding the current project by looping over all projects](https://github.com/wakatime/atom-wakatime/blob/3c7abf523f692df8979c3eee50d50fc5217d128e/lib/wakatime.coffee#L326)
2. [executing wakatime-cli in a background python process](https://github.com/wakatime/atom-wakatime/blob/3c7abf523f692df8979c3eee50d50fc5217d128e/lib/wakatime.coffee#L335)

How many project folders do you have open in Atom?

Executing wakatime-cli happens async, but maybe Atom somehow blocks other `onDidSave` events from executing.

**Comment by daveyjones** [comment]
I'm on a MacBook Pro running OS X 10.11.3. I only have 4 projects, so it's probably not 1. It seems like a conflict with `onDidSave` is more likely. The LESS compiler I'm using is [less-autocompile](https://atom.io/packages/less-autocompile). I haven't quite figured out exactly how to re-produce. I'm able to resolve the issue temporarily by resetting the wakatime plugin, but after a time the delay returns. I'll try to figure out the exact path to reproduce.

**Comment by daveyjones** [comment]
I think this may be related to #31. After each save, the CPU usage for Atom Helper is quite high (see screenshot). I wonder if Atom is waiting for this process to finish before executing other `onDidSave` events due to the high CPU usage. (I'm not sure if Atom is that smart.)

<img width="1440" alt="screen shot 2016-04-01 at 9 06 14 am" src="https://cloud.githubusercontent.com/assets/2852617/14212804/7e9ef100-f7e9-11e5-9fb4-881fe1f4a7e9.png">

**Comment by alanhamlett** [comment]
I can try using [BufferedProcess](https://atom.io/docs/api/v1.6.2/BufferedProcess) instead of [child_process.execFile](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) but the former is just a wrapper of the latter using `spawn` instead of `execFile` so I'm not sure it would make any difference.

With `wakatime` installed but `less-autocompile` plugin uninstalled, does Atom Helper still use such high CPU?

I'm not able to reproduce it with `less-autocompile` installed, but my LESS files don't have the custom `out`, `sourcemap`, ... parameters on the first line of the LESS file.

**Comment by daveyjones** [comment]
I'm actually going to close this issue. I don't think it's related to WakaTime at all. I've read that others are having issues with Atom Helper and high CPU usage. One suggestion I found was to disable the built-in `spell-check` package. This seems to have solved it for me.

**Comment by alanhamlett** [comment]
Oh that's a relief, I was stuck on this one. :relieved:
