### ISSUE TITLE
Code activity still stopped

### ISSUE THREAD

**Issue by ShavidzeT** [wakatime/atom-wakatime#55]
OS: ubunut 14.04 LTS
Wakatime still doesn't work on my pc, I think there is a huge problem.
~/.wakatime.log is empty also. Today I checked the wakatime website and there was no tracked time in my profile, so I lost whole day codign activity :angry:

**Comment by ShavidzeT** [comment]
Today I change my timezine in my wakatime profile, may it cause problem?

**Comment by alanhamlett** [comment]
Changing the timezone won't cause any problems, the only thing it could do is make your dashboard load slow the first time because your coding activity won't be cached in the new timezone yet.

Things to check:

1. Do you have the plugin enabled in Atom -> Preferences -> Packages
2. First, turn on debug mode in Atom -> Preferences -> Packages -> wakatime
3. Can you enter your api key in Atom -> Preferences -> Packages -> wakatime and does it save to ~/.wakatime.cfg afterwards
4. Do you have any errors in the Atom Developer Console (View -> Developer -> Toggle Developer Tools)

This may be related to #49

**Comment by alanhamlett** [comment]
@ShavidzeT are you using the email from your GitHub profile with WakaTime? Under that email I see a few hours of coding activity today... maybe you have two accounts?

**Comment by ShavidzeT** [comment]
I have no errors in devtools and also no errors in log files. I have a same email on github and on wakatime and so I haven't two accounts. Today morning my coding activiy was tracking but now it is stoped....
I dont know may it could some timw to show time on my profile...

**Comment by alanhamlett** [comment]
Let's move the discussion to #49 because this is the same issue.
