### ISSUE TITLE
'Retry' object has no attribute 'raise_on_status'

### ISSUE THREAD

**Issue by paveldruzyak** [wakatime/atom-wakatime#56]
After update to version 6.0.5 I got such error:
```
.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/packages/urllib3/util/retry.py\", line 147,
in new raise_on_status=self.raise_on_status,
AttributeError: 'Retry' object has no attribute 'raise_on_status'
```

**Comment by paveldruzyak** [comment]
rebooted laptop and problem disappeared

**Comment by alanhamlett** [comment]
This is a known bug in wakatime-cli wakatime/vim-wakatime#39. We are updating wakatime-cli to use urllib3 master to fix this, because it might be a while before the fix gets into the requests library.

It was fixed after rebooting because it's a network issue, so the bug only triggers when the api server is slow to respond.
