### ISSUE TITLE
status bar icon visible when setting set to hidden

### ISSUE THREAD

**Issue by danielbayley** [wakatime/atom-wakatime#59]
This package still shows the status bar item for every new window even though I have `showStatusBarIcon` set to `false`.

atom-wakatime 6.0.7
Atom 1.8.0
OS X 10.11.5

**Comment by alanhamlett** [comment]
Is the GUI checkbox in the wakatime settings turned off? The config value might be false but the namespace of the config might have changed at some point.

**Comment by danielbayley** [comment]
@alanhamlett Yep, I just deleted the line in config and unchecked the setting… same behaviour.
The value is still `showStatusBarIcon`.

**Comment by alanhamlett** [comment]
Can you clarify a few things:

1. When you check, then uncheck the `Show WakaTime in Atom status bar` setting does the icon toggle from visible to hidden?

2. Are there any errors in Atom's developer console when toggling the checkbox setting?

3. By "for every new window" do you mean opening a new instance of Atom, opening a new window with Atom already open, or opening a new tab?

Maybe it's a race condition, because I'm not able to reproduce it using OS X and Atom 1.8.0.

**Comment by danielbayley** [comment]
1. Yes
2. No
3. Opening a new instance of Atom or a new window with Atom already open shows the status bar item even with the setting unchecked. New tabs don't affect it.

So probably the logic in `activate: ->` somewhere is not quite right.

**Comment by alanhamlett** [comment]
Is it fixed in v6.0.8?

**Comment by danielbayley** [comment]
@alanhamlett Yep, working properly now 👍
