### ISSUE TITLE
Saving files causes whole system to lock up on Ubuntu

### ISSUE THREAD

**Issue by dfrankland** [wakatime/atom-wakatime#90]
I've combed through some of the other issues and have tried reinstalling the plugin, using different versions of the `wakatime` python package, disabled the `spell-check` plugin, turned debug logging on and off, and I still have problems on Ubuntu whenever I save a file. Seems to lock up on every invocation of the python module for whatever reason.

I'm running Ubuntu 19.04 with Atom 1.40.1.

**Comment by khaeru** [comment]
I was also running into this issue—triggered by Atom, but also by other code. It turns out the culprit is a Gnome Shell extension named "desktop-icons" that does exactly that: displays desktop icons. See:
- https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-desktop-icons/+bug/1812883
- https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/issues/58

In short, any change to any file in the desktop directory—even a hidden file like `.foo`—causes all the desktop icons to be regenerated. Since this is *not* done asynchronously, and if there is a lot of stuff on the desktop, it can cause a noticeable lock-up. Many users (including me, and probably @dfrankland) use `~` or `$HOME` as the desktop directory, so any program writing a `~/.whatever` configuration file triggers this action. 

atom-wakatime triggers this bug because wakatime, by default, keeps files ~/.wakatime.cfg, ~/.wakatime.cb, and ~/.wakatime.log; the second is modified frequently.

I tried to work around this by setting the `WAKATIME_HOME` environment variable in my `.profile`, so that wakatime keeps those files in a different directory. This seems to work, i.e. the lock-ups no longer occur.

In the process I encountered another bug, which I'll file separately.
